export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_SUBMIT = 'SIGN_IN_SUBMIT';
export const LOGOUT = 'LOGOUT';

export const CREATE_TASK_PICKED_TYPE = 'CREATE_TASK_PICKED_TYPE';
export const CREATE_TASK_SELECTED_DAY = 'CREATE_TASK_SELECTED_DAY';
export const CREATE_TASK_UN_SELECTED_DAY = 'CREATE_TASK_UN_SELECTED_DAY';
export const CREATE_TASK_STEP = 'CREATE_TASK_STEP';
export const CREATE_TASK_DATE_CHANGED_AT_INDEX = 'CREATE_TASK_DATE_CHANGED_AT_INDEX';
export const CREATE_TASK_FINISHED = 'CREATE_TASK_FINISHED';


export const LOAD_STATE_FROM_DATABASE = 'LOAD_STATE_FROM_DATABASE';



