export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_SUBMIT = 'SIGN_IN_SUBMIT';
export const LOGOUT = 'LOGOUT';

export const CREATE_TASK_PICKED_TYPE = 'CREATE_TASK_PICKED_TYPE';
export const CREATE_TASK_SELECTED_DAY = 'CREATE_TASK_SELECTED_DAY';
export const CREATE_TASK_UN_SELECTED_DAY = 'CREATE_TASK_UN_SELECTED_DAY';
export const CREATE_TASK_STEP = 'CREATE_TASK_STEP';
export const CREATE_TASK_DATE_CHANGED_AT_INDEX = 'CREATE_TASK_DATE_CHANGED_AT_INDEX';
export const CREATE_TASK_FINISHED = 'CREATE_TASK_FINISHED';

export const TASK_CHANGES_TASKS_UPDATED = "TASK_CHANGES_TASKS_UPDATED";


export const LOAD_STATE_FROM_DATABASE = 'LOAD_STATE_FROM_DATABASE';

export const  EDIT_TASK_START_EDITING = "START_EDITING_TASK";
export const  EDIT_TASK_CANCEL_EDITING = "EDIT_TASK_CANCEL_EDITING";
export const  EDIT_TASK_ADD_DAY = "EDIT_TASK_ADD_DAY";
export const  EDIT_TASK_REMOVE_DAY = "EDIT_TASK_REMOVE_DAY";
export const  EDIT_TASK_REMOVE_TIME = "EDIT_TASK_REMOVE_TIME";
export const  EDIT_TASK_DATE_CHANGED_AT_INDEX = "EDIT_TASK_DATE_CHANGED_AT_INDEX";
export const  EDIT_TASK_END_EDITING = "EDIT_TASK_END_EDITING";







